name: Bump and Deploy

on:
  push:
    branches: [master]

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    outputs:
      newTag: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: cat package.json
        run: cat ./package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
          minor-wording: 'MINOR'
          major-wording: 'MAJOR'
          patch-wording: 'PATCH'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cat package.json
        run: cat ./package.json

      - name: Create New Tag
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  create_release:
    needs: bump-version
    if: startsWith(needs.bump-version.outputs.newTag, 'v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Get tag from previous job
        run: echo "Generating release with the ${{needs.bump-version.outputs.newTag}} tag"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.bump-version.outputs.newTag}}
          release_name: Release ${{needs.bump-version.outputs.newTag}}
          draft: false
          prerelease: false
