name: Manual check

on:
  workflow_run:
    #branches:
    #- "*"
    workflows:
      - "Release (Jar-Github-S3)"
      - release.yml
    types:
      - completed
    #tags:
    #- "v*"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: staging
        description: Select environment
        options:
          - staging
          - production
        required: true
      version:
        default: ""
        description: Version; v1.2.3 or empty for latest
        required: false
      script-check:
        default: "true"
        type: boolean
        description: (Production only) If you have migration script to run, do not forget to run
        required: false

env:
  NODE_VERSION: 14.x

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test output
        env:
          IS_VALID: ${{ github.event.inputs.environment }}
        run: echo "env $IS_VALID"
