name: Publish to NPM
env:
  NODE_VERSION: 14.x

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      #- name: Run tests??
      #  run: yarn test
      - name: Create build
        run: yarn build

      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}