name: Test

on:
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: 14.x

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: yarn

      - name: Commit Author Action
        id: semcelik
        uses: semcelik/commit-author-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          email_domain: "@gmail.com"
          error_on_fail: true

      - name: test output
        env:
          IS_VALID: ${{ steps.semcelik.outputs.is_valid }}
        run: echo "isValid $IS_VALID"
